spring:
  application:
    name: connections-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: admin1234
  data:
    neo4j:
      database: linkedinapp
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nr3101.*


server:
  port: 9030
  servlet:
    context-path: /connections